In [3]:
from pyiron_atomistics import Project 
%config IPCompleter.evaluation='unsafe'

In [4]:
import ase

In [5]:
pr = Project('read-extxyz-to-ase')

In [8]:
structure = pr.create.structure.ase('Ni_crack-block_1.xyz')

TypeError: 'AseFactory' object is not callable

In [9]:
from ase.io import read
atoms = read('Ni_crack-block_1.xyz')


KeyError: '2'

In [6]:
from ase.lattice.cubic import FaceCenteredCubic
ase_atoms = FaceCenteredCubic(directions = [[1, 1, 2], [-1, 1, 0], [-1, -1, 1]],
                          size=(4, 4, 20),
                          symbol='Ni',
                          pbc=(1,1,0),
                         latticeconstant = 3.52)

In [7]:
import numpy as np

In [8]:
atom_ids = np.arange(1, len(ase_atoms) + 1)

In [9]:
ase_atoms.set_array('ids', atom_ids)

In [10]:
ase_atoms.get_positions()

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.15555097e+00, 1.24450793e+00, 2.09408937e-16],
       [7.18516991e-01, 1.24450793e+00, 2.03227295e+00],
       ...,
       [1.58073738e+01, 7.46704761e+00, 1.17871831e+02],
       [1.43703398e+01, 7.46704761e+00, 1.19904104e+02],
       [1.65258908e+01, 8.71155554e+00, 1.19904104e+02]])

In [11]:
max_pos = np.max(ase_atoms.get_positions()[:,2])

is_bottom = ase_atoms.get_positions()[:,2] < 15
is_top = ase_atoms.get_positions()[:,2] >= max_pos - 15
is_top

array([False, False, False, ...,  True,  True,  True])

In [12]:
atom_flags = np.zeros(len(ase_atoms))
atom_flags[is_top] = 1
atom_flags[is_bottom] = 2
print(atom_flags)

[2. 2. 2. ... 1. 1. 1.]


In [16]:
import numpy as np
from contextlib import contextmanager

@contextmanager
def show_complete_array():
    oldoptions = np.get_printoptions()
    np.set_printoptions(threshold=np.inf)
    try:
        yield
    finally:
        np.set_printoptions(**oldoptions)

In [25]:
np.set_printoptions(threshold=np.inf, linewidth=200)
ase_atoms.arrays

{'numbers': array([28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28,
        28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28,
        28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28,
        28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28,
        28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 2

In [13]:
ase_atoms.set_array('flags', atom_flags)

Lattice(symbols='Ni1920', pbc=[True, True, False], cell=[17.244407789193577, 9.95606347910659, 121.93637685284898], flags=..., ids=...)


In [45]:
pr = Project('use-ase-tags')
structure = pr.create.structure.from_ase(ase_atoms)

In [46]:
structure.plot3d()

NGLWidget()

In [47]:
structure

Ni: [0. 0. 0.]
Ni: [2.15555097e+00 1.24450793e+00 2.09408937e-16]
Ni: [0.71851699 1.24450793 2.03227295]
Ni: [2.87406796e+00 8.18316247e-17 2.03227295e+00]
Ni: [ 1.43703398e+00 -1.99784055e-16  4.06454590e+00]
Ni: [3.59258496 1.24450793 4.0645459 ]
Ni: [4.31110195e+00 9.60045998e-17 2.87324730e-16]
Ni: [6.46665292e+00 1.24450793e+00 4.96733667e-16]
Ni: [5.02961894 1.24450793 2.03227295]
Ni: [7.18516991e+00 1.77836225e-16 2.03227295e+00]
Ni: [ 5.74813593e+00 -1.03779455e-16  4.06454590e+00]
Ni: [7.9036869  1.24450793 4.0645459 ]
Ni: [8.62220389e+00 1.92009200e-16 5.74649461e-16]
Ni: [1.07777549e+01 1.24450793e+00 7.84058398e-16]
Ni: [9.34072089 1.24450793 2.03227295]
Ni: [1.14962719e+01 2.73840824e-16 2.03227295e+00]
Ni: [ 1.00592379e+01 -7.77485557e-18  4.06454590e+00]
Ni: [12.21478885  1.24450793  4.0645459 ]
Ni: [1.29333058e+01 2.88013799e-16 8.61974191e-16]
Ni: [1.50888568e+01 1.24450793e+00 1.07138313e-15]
Ni: [13.65182283  1.24450793  2.03227295]
Ni: [1.58073738e+01 3.69845424e-16

In [15]:
ase_atoms.set_constraint?

Signature: ase_atoms.set_constraint(constraint=None)
Docstring:
Apply one or more constrains.

The *constraint* argument must be one constraint object or a
list of constraint objects.
File:      /cmmc/ptmp/pyironhb/mambaforge/envs/pyiron_mpie_cmti_2024-09-02/lib/python3.11/site-packages/ase/atoms.py
Type:      method

In [27]:
pr = Project('use-ase-tags')
structure = pr.create.structure.from_ase(ase_atoms)

In [28]:
#structure.plot3d()

In [29]:
import numpy as np
num = structure.get_number_of_atoms()
max_pos = np.max(structure.get_positions()[:][:,2])
min_pos = np.min(structure.get_positions()[:][:,2])

In [30]:
#is_bottom = np.zeros(num)
is_top = structure.positions[:][:,2] >= max_pos-15.
is_center = (structure.positions[:][:,2] < max_pos-15.) & (structure.positions[:][:,2] >= min_pos+15.)
is_bottom = structure.positions[:][:,2] < min_pos+15.
is_bottom

array([ True,  True,  True, ..., False, False, False])

In [31]:
structure.set_tags(is_bottom)
#structure.set_tags(is_center*2)
#structure.set_tags(is_top*3)
structure.set_tags(is_bottom+is_center*2+is_top*3)

In [32]:
structure.tags

array([1, 1, 1, ..., 3, 3, 3])

In [33]:
#import numpy as np
#structure.indices = np.arange(0, structure.get_number_of_atoms())[:]

In [34]:
structure.indices
# INDEX ENCODES ELEMENT!

array([0, 0, 0, ..., 0, 0, 0])

In [35]:
structure.indices = np.arange(0, structure.get_number_of_atoms())

In [36]:
structure.indices

array([   0,    1,    2, ..., 1917, 1918, 1919])

In [38]:
structure

IndexError: list index out of range

In [24]:
structure.plot3d()

IndexError: list index out of range

In [39]:
import ase 

In [42]:
ase.io.iread??

Signature:
ase.io.iread(
    filename: Union[str, pathlib.PurePath, IO],
    index: Any = None,
    format: str = None,
    parallel: bool = True,
    do_not_split_by_at_sign: bool = False,
    **kwargs,
) -> Iterable[ase.atoms.Atoms]
Source:   
def iread(
        filename: NameOrFile,
        index: Any = None,
        format: str = None,
        parallel: bool = True,
        do_not_split_by_at_sign: bool = False,
        **kwargs
) -> Iterable[Atoms]:
    """Iterator for reading Atoms objects from file.

    Works as the `read` function, but yields one Atoms object at a time
    instead of all at once."""

    if isinstance(filename, PurePath):
        filename = str(filename)

    if isinstance(index, str):
        index = string2index(index)

    filename, index = parse_filename(filename, index, do_not_split_by_at_sign)

    if index is None or index == ':':
        index = slice(None, None, None)

    if not isinstance(index, (slice, str)):
        index = slice(index, (index + 1